/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.distribuidos;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author A-SOFT03
 */
public class Principal extends javax.swing.JFrame {

    private Conexion conexion;
    private String[] cabeceraMensajes;
    String idMensaje;

    /**
     * Creates new form Principal
     */
    public Principal(Conexion conexion) {
        initComponents();
        
        this.conexion = conexion;

        conexion.enviarComando("STAT");
        conexion.listarMensajes();

        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Ingrese ID del mensaje");

        try {
            while (!(idMensaje = br.readLine()).equals("exit")) {
                conexion.mostrarCorreo(idMensaje);
            }
            conexion.cerrarConexion();
        } catch (IOException ex) {
            System.out.println("Error al leer deste teclado el ID del mensaje");
            ex.printStackTrace();
        }
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsola = new javax.swing.JScrollPane();
        lblConsola = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCorreo = new javax.swing.JMenu();
        menuModo = new javax.swing.JMenu();
        radioModoCG = new javax.swing.JRadioButtonMenuItem();
        radioModoCB = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConsola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConsola.setText("Consola");

        menuCorreo.setText("Correo");
        menuBar.add(menuCorreo);

        menuModo.setText("Modo");

        radioModoCG.setSelected(true);
        radioModoCG.setText("jRadioButtonMenuItem2");
        radioModoCG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModoCGActionPerformed(evt);
            }
        });
        menuModo.add(radioModoCG);

        radioModoCB.setText("jRadioButtonMenuItem1");
        menuModo.add(radioModoCB);

        menuBar.add(menuModo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConsola)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConsola)
                        .addGap(0, 507, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(lblConsola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioModoCGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModoCGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioModoCGActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblConsola;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCorreo;
    private javax.swing.JMenu menuModo;
    private javax.swing.JScrollPane panelConsola;
    private javax.swing.JRadioButtonMenuItem radioModoCB;
    private javax.swing.JRadioButtonMenuItem radioModoCG;
    // End of variables declaration//GEN-END:variables
}
